#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CHORDAL_HOLD
#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY

#define SPLIT_TRANSPORT_MIRROR
