#pragma once

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CHORDAL_HOLD
#define TAPPING_TERM 200
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY

#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_BAND_SPIRAL_VAL
#define RGB_MATRIX_DEFAULT_VAL 100
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_HUE 0
